### ISSUE TITLE
Getting 'GeometryCollection' has no len() when running the cut_gtfs function

### ISSUE THREAD

**Issue by ayronguerra** [Bondify/gtfs_functions#15]
I can run the previous functions that don't depend on the segments_gdf but I get the error when running the cut_gtfs function.
<img width="833" alt="Screen Shot 2022-12-22 at 9 49 53 AM" src="https://user-images.githubusercontent.com/48091959/209171850-e0f9c889-9a14-4235-ab40-c5d75632691b.png">

**Comment by yeying123** [comment]
I run into the same error message when processing various GTFS files. Any solution?

**Comment by ayronguerra** [comment]
Not yet, I emailed @Bondify but I haven't get a response. @yeying123 Please let me know if you solve the issue

**Comment by yeying123** [comment]
@ayronguerra - Got time to look into the error this week. I think the issue was because the the result comes as the type 'GeometryCollection' and we need to add `.geoms`  in order to read the length of it. 

I modified the source code to add `.geoms` to line 330, which becomes `if len(result.geoms) == len(trans_lines_all.geoms)-1:`.

**Comment by Bondify** [comment]
hi @Narmina , we are about to release an updated that deals with this issues. How urgent is this for you?

**Comment by Narmina** [comment]
Hello @Bondify, thank you!
the sooner the better

**Comment by yeying123** [comment]
@Narmina - if you want to do a quick fix on your end, try to replace it with `d['segment'] = [s for s in result.geoms]`. It should fix the error.
